/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lab5.XFile;

/**
 *
 * @author macos
 */
public class mainJFrame extends javax.swing.JFrame {
    private List<NhanVien_mainJFrame> list = new ArrayList<>();
    DefaultTableModel tblModel;
    
    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
        setLocationRelativeTo(null);//run ra giua
        initTable();
        
    }
    public void initTable(){
        tblModel = (DefaultTableModel) tblBang.getModel();
        String[] cols = new String[] {"Mã NV","Họ và Tên","gioi tinh","vai tro"};
        tblModel.setColumnIdentifiers(cols);
    }
    public void fillToTable(){
        tblModel.setRowCount(0);
        for(NhanVien_mainJFrame nv: list ){
            Object[] row = new Object[]{nv.getMa(),nv.getName(),nv.getGioiTinh(),nv.getVaiTro()};
            tblModel.addRow(row);
        }
    }
    public void clean(){
        txtMa.setText(null);
        txtName.setText(null);
//        rdbNu.setSelected(false);
        rdbNam.setSelected(false);
        cbbChucVu.setSelectedIndex(0);
        tblBang.clearSelection();
    }
    public void showDetail(int index){
    
        txtMa.setText(list.get(index).getMa());
        txtName.setText(list.get(index).getName());
        if(list.get(index).getGioiTinh().equalsIgnoreCase("nữ")){
            rdbNu.setSelected(true);
        }else{
            rdbNam.setSelected(true);
        }
        if(list.get(index).getVaiTro().equalsIgnoreCase("trưởng phòng")){
            cbbChucVu.setSelectedIndex(0);
        }else{
            cbbChucVu.setSelectedIndex(1);
        }
        
    }
    public void saveFile(){
        try {
            XFile.writeObject("/Users/macos/Desktop/thong/java/java2/dataJava2/data2.txt",list);
            JOptionPane.showMessageDialog(this, "Lưu thành công");
        } catch (IOException ex) {
            ex.getMessage();
        }
    }
    public void openFile(){
        try{
            list = (List<NhanVien_mainJFrame>) XFile.readObject("/Users/macos/Desktop/thong/java/java2/dataJava2/data2.txt");
        }catch(Exception ex){
            ex.getMessage();
        }
    }
    //sap xep chu
    public void sapXepMaNV(){
        Comparator<NhanVien_mainJFrame> comp = new Comparator<NhanVien_mainJFrame>() {
            @Override
            public int compare(NhanVien_mainJFrame o1, NhanVien_mainJFrame o2) {
                return (o1.getMa().compareTo(o2.getMa()));
            }
        };
        Collections.sort(list, comp);
        fillToTable();
    }
    public void sapXepName(){
        Comparator<NhanVien_mainJFrame> comp = new Comparator<NhanVien_mainJFrame>() {
            @Override
            public int compare(NhanVien_mainJFrame o1, NhanVien_mainJFrame o2) {
                return (o1.getName().compareTo(o2.getName()));
            }
        };
        Collections.sort(list, comp);
        fillToTable();
    }
    public void sapXepGioiTinh(){
        Comparator<NhanVien_mainJFrame> comp = new Comparator<NhanVien_mainJFrame>() {
            @Override
            public int compare(NhanVien_mainJFrame o1, NhanVien_mainJFrame o2) {
                return (o1.getGioiTinh().compareTo(o2.getGioiTinh()));
            }
        };
        Collections.sort(list, comp);
        fillToTable();
    }
    public void sapXepChucVu(){
        Comparator<NhanVien_mainJFrame> comp = new Comparator<NhanVien_mainJFrame>() {
            @Override
            public int compare(NhanVien_mainJFrame o1, NhanVien_mainJFrame o2) {
                return (o1.getVaiTro().compareTo(o2.getVaiTro()));
            }
        };
        Collections.sort(list, comp);
        fillToTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPaneGioiTinh = new javax.swing.JPanel();
        rdbNu = new javax.swing.JRadioButton();
        rdbNam = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbbChucVu = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbbSapXep = new javax.swing.JComboBox<>();
        btnSapXep = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Quản lý Nhân viên");

        buttonGroup1.add(rdbNu);
        rdbNu.setText("nữ");

        buttonGroup1.add(rdbNam);
        rdbNam.setText("nam");

        jLabel4.setText("gioi tinh");

        javax.swing.GroupLayout JPaneGioiTinhLayout = new javax.swing.GroupLayout(JPaneGioiTinh);
        JPaneGioiTinh.setLayout(JPaneGioiTinhLayout);
        JPaneGioiTinhLayout.setHorizontalGroup(
            JPaneGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneGioiTinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPaneGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPaneGioiTinhLayout.createSequentialGroup()
                        .addComponent(rdbNu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbNam))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPaneGioiTinhLayout.setVerticalGroup(
            JPaneGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneGioiTinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPaneGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbNu)
                    .addComponent(rdbNam))
                .addGap(20, 20, 20))
        );

        jLabel3.setText("Ma NV");

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        jLabel5.setText("Họ và Tên");

        jLabel6.setText("chuc vu");

        cbbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "trưởng phòng", "nhân viên" }));

        btnThem.setText("thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setText("lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnDoc.setText("đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        jButton1.setText("|<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(">|");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ma NV", "Họ Và Tên", "Giới Tính", "Chức Vụ" }));
        cbbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSapXepActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        jLabel7.setText("Sắp xếp theo ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPaneGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(235, 235, 235))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(117, 117, 117))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSapXep)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSua)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JPaneGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addGap(27, 27, 27)
                        .addComponent(btnMoi)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuu)
                            .addComponent(btnDoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSapXep))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(new String(txtMa.getText()).equals("")){
            txtMa.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Chua nhap ma nv!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (NhanVien_mainJFrame nv : list) {
            if (nv.getMa().equals(txtMa.getText())) {
                JOptionPane.showMessageDialog(this, "Ma NV đã tồn tại!", "Error", JOptionPane.WARNING_MESSAGE);
                break;
            }
        }
        if(new String(txtName.getText()).equals("")){
            txtName.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Chua nhap ho và tên!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(rdbNu.isSelected()==false && rdbNam.isSelected()==false){
            JPaneGioiTinh.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Chua chon gio tinh!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        txtMa.setBackground(Color.WHITE);
        txtName.setBackground(Color.WHITE);
        JPaneGioiTinh.setBackground(Color.WHITE);
        
        NhanVien_mainJFrame nv = new NhanVien_mainJFrame();
        nv.setMa(txtMa.getText());
        nv.setName(txtName.getText());
        if(rdbNu.isSelected()==false){
            nv.setGioiTinh("nam");
        }else{
            nv.setGioiTinh("nu");
        }
        nv.setVaiTro((String)cbbChucVu.getSelectedItem());
        list.add(nv);
        fillToTable();
        clean();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clean();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(txtMa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Chua nhap Ma NV!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //xoa
        for(NhanVien_mainJFrame i: list){
            if(i.getMa().equals(txtMa.getText())){
                int choice = (JOptionPane.showConfirmDialog(this, "Detele ?", "confirm", JOptionPane.YES_NO_OPTION));
                
                if(choice == JOptionPane.YES_OPTION){
                    list.remove(i);
                    fillToTable();
                    JOptionPane.showMessageDialog(this, "da xoa");
                    clean();
                    return;
                }else{                  
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Ma NV khong ton tai!");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         if(txtMa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Chua nhap Ma NV!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(new String(txtName.getText()).equals("")){
            txtName.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Chua nhap ho va ten!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(rdbNu.isSelected()==false && rdbNam.isSelected()==false){
            JPaneGioiTinh.setBackground(Color.YELLOW);
            JOptionPane.showMessageDialog(this, "Chua chon gio tinh!", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        txtMa.setBackground(Color.WHITE);
        txtName.setBackground(Color.WHITE);
        JPaneGioiTinh.setBackground(Color.WHITE);
         for(NhanVien_mainJFrame nv: list){
            if(nv.getMa().equals(txtMa.getText())){               
                nv.setName(txtName.getText());
                if(rdbNu.isSelected()==false){
                    nv.setGioiTinh("nam");
                }else{
                    nv.setGioiTinh("nu");
                }
                nv.setVaiTro((String)cbbChucVu.getSelectedItem());   
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                fillToTable();
                clean();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Ma NV không tồn tại!");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        int index = tblBang.getSelectedRow();
        showDetail(index);
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        saveFile();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        openFile();
        fillToTable();
    }//GEN-LAST:event_btnDocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //quay ve 0
//        int index = tblBang.getSelectedRow();
//        index = 0;
//        showDetail(index);
        tblBang.setRowSelectionInterval(0, 0);
        
        //        tblDanhSachNV.setSelectedRow(index);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // lui ve -1
        int index = tblBang.getSelectedRow();
        if(index==0){
            index =list.size()-1;
            showDetail(index);   
        }else
        {
            index--;
            showDetail(index);
        }
        tblBang.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //len +1
        int index = tblBang.getSelectedRow();
        if(index == list.size()-1){
            index = 0;
            showDetail(index);
        }else{
            index++;
            showDetail(index);   
        }
        tblBang.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //len n-1
//        int index = tblBang.getSelectedRow();
//        index = list.size()-1;
//        showDetail(index);
        tblBang.setRowSelectionInterval(list.size()-1, list.size()-1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        
        if(cbbSapXep.getSelectedIndex()==0){
            sapXepMaNV();
        }
        if(cbbSapXep.getSelectedIndex()==1){
            sapXepName();
        }
        if(cbbSapXep.getSelectedIndex()==2){
            sapXepGioiTinh();
        }
        if(cbbSapXep.getSelectedIndex()==3){
            sapXepChucVu();
        }
//        int n =cbbSapXep.getSelectedIndex();
//        switch(n){
//            case 1:{
//                sapXepMaNV();
//                break;
//            }
//            case 2:{
//                sapXepName();
//                break;
//            }
//            case 3:{
//                sapXepGioiTinh();
//                break;
//            }
//            case 4:{
//                sapXepChucVu();
//                break;
//            }
//        }
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void cbbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSapXepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSapXepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneGioiTinh;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbSapXep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
