/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testLab7;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lab5.XFile;

/**
 *
 * @author macos
 */
public class from extends javax.swing.JFrame {
    List<SinhVienTim> listTim = new ArrayList<>();
    List<SinhVien> listSV = new ArrayList<>();
    DefaultTableModel tblModel;
    /**
     * Creates new form from
     */
    public from(String name) {
        initComponents();
        setLocationRelativeTo(null);
        lblChao.setText(name);
        initTable();
        tao();
        fillToTable(listSV);
    }
    //tao sv
    public void tao(){
        SinhVien sv1 = new SinhVien("123","Nguyễn Văn A",4.5f,"CNTT");
        SinhVien sv2 = new SinhVien("456","Nguyễn Văn B",9.5f,"TKDT");
        SinhVien sv3 = new SinhVien("789","Nguyễn Văn C",3.0f,"CNTT");
        SinhVien sv4 = new SinhVien("444","Nguyễn Văn D",5.5f,"CNTT");
        listSV.add(sv1);
        listSV.add(sv2);
        listSV.add(sv3);
        listSV.add(sv4);
    }
    
    //set colum table
    public void initTable(){
        tblModel = (DefaultTableModel) tblBang.getModel();
        String[] cols = new String[] {"Mã ","Họ và Tên","Tuổi","Ngành"};
        tblModel.setColumnIdentifiers(cols);
    }
    public void fillToTable(Object list){
        tblModel.setRowCount(0);
        for(SinhVien sv: (List<SinhVien>)(Object)list ){
            Object[] row = new Object[]{sv.getMa(),sv.getName(),sv.getDiem(),sv.getNganh()};
            tblModel.addRow(row);
        }
    }
    public void tim(){
        listTim.clear();
        for(int i=0;i<listSV.size();i++){
            if(listSV.get(i).getName().contains(txtTim.getText())){
                SinhVienTim svTim = new SinhVienTim();
                svTim.setMa(listSV.get(i).getMa());
                svTim.setName(listSV.get(i).getName());
                svTim.setDiem(listSV.get(i).getDiem());
                svTim.setNganh(listSV.get(i).getNganh());
                svTim.setIndex(i);
                listTim.add(svTim);
            }
        }
        fillToTable(listTim);
    }
    public void xoa(int index){
        int choice = (JOptionPane.showConfirmDialog(this, "ban co chac chac muon xoa ?", "thông báo", JOptionPane.YES_NO_OPTION));
        
                if(choice ==0){
                    if(listSV.size()==listTim.size()||listTim.size()==0){
                        if(tblBang.getSelectedRow()>=0){
                            int i=tblBang.getSelectedRow();
                            listSV.remove(i);
                            fillToTable(listSV);
                            
                        }else{
                            JOptionPane.showConfirmDialog(this, "chọn sv cần xóa!");
                        }
                    
                    
                    }else{
                        String maSV = tblBang.getValueAt(tblBang.getSelectedRow(), 0).toString();
                        int vitri = -1;
                        for(SinhVienTim i: listTim){
                            if(i.getMa().equalsIgnoreCase(maSV)){
                                vitri = i.getIndex();
                                break;
                            }
                            listTim.clear();
                            listSV.remove(i);
                            fillToTable(listSV);
                        }
                        
                    }
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        lblChao = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBang);

        lblChao.setText("chao");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });
        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKeyPressed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnThoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblChao)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim)
                        .addGap(73, 73, 73)
                        .addComponent(btnXoa)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChao)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(btnXoa))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int choice = (JOptionPane.showConfirmDialog(this, "ban co muon qua ve login ?", "thông báo", JOptionPane.YES_NO_OPTION));
        
                if(choice == JOptionPane.YES_OPTION){
                    this.dispose();
                    new Login().setVisible(true);
                }else{
                    System.exit(0);
                }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        tim();
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        tim();
    }//GEN-LAST:event_txtTimActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        xoa(tblBang.getSelectedRow());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyPressed
        tim();
    }//GEN-LAST:event_txtTimKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChao;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
